export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const SELECT_USER = "SELECT_USER";

export const FETCH_USER_ALBUMS_REQUEST = "FETCH_USER_ALBUMS_REQUEST";
export const FETCH_USER_ALBUMS_SUCCESS = "FETCH_USER_ALBUMS_SUCCESS";
export const FETCH_USER_ALBUMS_FAILURE = "FETCH_USER_ALBUMS_FAILURE";
export const FETCH_PHOTOS_REQUEST = "FETCH_PHOTOS_REQUEST";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAILURE = "FETCH_PHOTOS_FAILURE";
export const SET_PHOTO = "SET_PHOTO";
export const UNSET_PHOTO = "UNSET_PHOTO"

export const FETCH_USER_POSTS_REQUEST = "FETCH_USER_POSTS_REQUEST";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const FETCH_USER_POSTS_FAILURE = "FETCH_USER_POSTS_FAILURE";
export const SET_USER_POST = "SET_CURRENT_POST";

export const FETCH_POST_COMMENTS_REQUEST = "FETCH_POST_COMMENTS_REQUEST";
export const FETCH_POST_COMMENTS_SUCCESS = "FETCH_POST_COMMENTS_SUCCESS";
export const FETCH_POST_COMMENTS_FAILURE = "FETCH_POST_COMMENTS_FAILURE";

export const FETCH_USER_TODOS_REQUEST = "FETCH_USER_TODOS_REQUEST";
export const FETCH_USER_TODOS_SUCCESS = "FETCH_USER_TODOS_SUCCESS";
export const FETCH_USER_TODOS_FAILURE = "FETCH_USER_TODOS_FAILURE";
